import type { Metadata } from "next";
import { unstable_ViewTransition as ViewTransition } from "react";
import { Geist, Geist_Mono } from "next/font/google";

import { NotificationProvider } from "@/context/NotificationContext";
import { SignalProvider } from "@/context/SignalContext";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ViewTransition>
          <NotificationProvider>
            <SignalProvider>{children}</SignalProvider>
          </NotificationProvider>
        </ViewTransition>
      </body>
    </html>
  );
}
